apiVersion: ENC[AES256_GCM,data:fnv0QwCEA6BR23kv,iv:Au4lSckNRy1f/B5hDDgYGhxcsCH7ecPTD3P+5s4xRDU=,tag:yof7pfqRnGBwfFKdTk/6EQ==,type:str]
kind: ENC[AES256_GCM,data:ocyHec9YyNWLBA==,iv:0fYi9Smq85R+SxPud4Huukqp+uLmbhlxCzPYWJ+jLZI=,tag:UCONk13Hq6MXSk/Uzo/VIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+8Ep2uc=,iv:bVqpmCPAIf5vTWS0iS4/+dSOgEx1Au31Yv0ubcRDcWc=,tag:oNqjMAjNbPXSciXNbbNzDA==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:Ng==,iv:g8+gB3xUmYopiESWuH+jL0QT4pBM4SynWgXZTrhVkv8=,tag:BksrmWfoVXr6MwyNyhD0Eg==,type:int]
    revisionHistoryLimit: ENC[AES256_GCM,data:4Q==,iv:gB+wwqb4VuwdXcAsZzNmwEwbEQbUMwTR1waglw7fGzg=,tag:iw2s99kP/vml0C1hoVl2yg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:oCUfjYM=,iv:TM3VGSgvm/9H4onC4Nq7Li78fkcLLZg7GOKs9kqTHzc=,tag:+1+7FP2Vhv9U6CogvXOeLA==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:AbVBMVI=,iv:kz1f4yUJVRVanHfyOMqcHDbpxbeiyhjtDpReBAZIFRY=,tag:CXWC8UgDjb19XbJj7+XCSg==,type:str]
        spec:
            containers:
            -   image: ENC[AES256_GCM,data:4yFNpFA=,iv:qmiHz6xooQnwANsbEn2oTrXnYDpkIZpLS+T0snHNzjA=,tag:bvfRADUqb7P/+/b2CHlLWA==,type:str]
                name: ENC[AES256_GCM,data:8VWvkVQ=,iv:7CEycAzRZNxT4mSNXkHipp97t2dQw3NwtVoYPAwl7aA=,tag:2znOaJh8vYZ5ZCJKWdSDKw==,type:str]
                ports:
                -   containerPort: ENC[AES256_GCM,data:i1M=,iv:uSKahN3DTf0RHw88vcGeyGOmQpzsc9xkyBmCxdD/+to=,tag:nScy5rn7eAVlAID3kionyw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-01-08T11:59:10Z'
    mac: ENC[AES256_GCM,data:KbZTu+A/d7KyT+ab7v42m1E9UXGYRBTOTK0oUvW9rFfp4VYUcP5UPRKKU4A8m9FqOX3Q+fB/Y+7HNt88gwxIEPX47Jtm6hC7E8L7wLEn3JUGU0Oud71/0fSu+WXY5GjbgexZYtMQGbg1opWAojJV6CTEFfM8qBawOLH1ujxCo1U=,iv:d3UpEMVflK1MgYewUqaqxKB04TtgfbPAhVmEu2Licns=,tag:0M6bCMjNnHta5ExIRjan2w==,type:str]
    pgp:
    -   created_at: '2020-01-08T08:38:10Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA1F+SjipM06IAQf/ZTVzlqo4qX2MbtVNoQ7bgH3s5P1bYFul+5VUUbfvAZDr
            G123/rUX3eZY5zWFehhN7ZOv8VyB6WEDCUmtg05mIRyBn5Pxnu3jVZDE5Cb4HysN
            UnXwe8cO+YJLJGgE7RJbA6ISMxir+eml309U+QKxOxtEAoakLmRiMYW12+pKQuiF
            Zgl7W8Lu0kEtOXvH2WRvLY00uDylSsPY9wSs35pqPlFlj6TD2GpNi8XpYmLVFUyF
            oBBxtCYiUXYI95xPtOVXFToZhhmdDRA9DCxCTUheOzBRbtT/S/AITJ3dxnkQYaSN
            xafttgbBPpbmVMnURMZeue0Y8+1dFAG14MEbKvsYPNJeASRF7CSHQN09lW8FdDsF
            PNH07VyPKPjtdBlYNmGAzbVpH3KwrQoi5rMmoNlO2J2nLkJAh1edcTuQyZMZ7IbZ
            IsX4Xg0h7+q7LOTndpYlEk6WZa9AA6BA/2835BD9iw==
            =DwdN
            -----END PGP MESSAGE-----
        fp: BB00448FB15EE8526FB1A4A46FE4F6879704BF7C
    unencrypted_suffix: _unencrypted
    version: 3.5.0
