apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apache-webserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apache-webserver
  template:
    metadata:
      labels:
        app: apache-webserver
    spec:
      containers:
      - image: apache
        name: apache-webserver
        ports:
        - containerPort: 80